import { SmsProvider, TransactionType } from "@prisma/client";
import { extractAmount, extractPhone, extractReference, finalizeParsedSms } from "./helpers";
import { airtelMoneyParser } from "./airtel-money";
import { crdbParser } from "./crdb";
import { halopesaParser } from "./halopesa";
import { mixxByYasParser } from "./mixx-by-yas";
import { mpesaParser } from "./mpesa";
import { nmbParser } from "./nmb";
import { selcomPesaParser } from "./selcom-pesa";
import type { ParsedSmsResult, SmsParserFixture, SmsParserModule } from "./types";

const parserModules: SmsParserModule[] = [
  mpesaParser,
  airtelMoneyParser,
  mixxByYasParser,
  halopesaParser,
  crdbParser,
  nmbParser,
  selcomPesaParser,
];

const fallbackTypeMatchers: Array<{ type: TransactionType; patterns: RegExp[] }> = [
  { type: "DEPOSIT", patterns: [/deposit/i, /cash\s?in/i, /umepokea/i, /received/i] },
  { type: "WITHDRAWAL", patterns: [/withdraw/i, /cash\s?out/i, /umetoa/i] },
  { type: "FLOAT_PURCHASE", patterns: [/float\s?purchase/i, /float/i, /top\s?up/i] },
  { type: "BILL_PAYMENT", patterns: [/bill\s?payment/i, /control\s?number/i] },
  { type: "MERCHANT_PAYMENT", patterns: [/merchant\s?payment/i, /lipa/i, /pay\s?merchant/i] },
  { type: "TRANSFER", patterns: [/transfer/i, /send money/i, /umetuma/i] },
  { type: "BANK_DEPOSIT", patterns: [/bank\s?deposit/i, /deposit to bank/i] },
  { type: "BANK_WITHDRAWAL", patterns: [/bank\s?withdraw/i, /withdraw from bank/i] },
];

function detectProvider(message: string, sender?: string, hint?: SmsProvider) {
  if (hint && hint !== "UNKNOWN") return hint;

  const parser = parserModules.find((candidate) => candidate.matches(message, sender));
  return parser?.provider ?? "UNKNOWN";
}

function fallbackParse(message: string, providerHint?: SmsProvider): ParsedSmsResult {
  const type = fallbackTypeMatchers.find(({ patterns }) =>
    patterns.some((pattern) => pattern.test(message))
  )?.type;
  const provider = detectProvider(message, undefined, providerHint);

  return finalizeParsedSms({
    provider,
    type,
    amount: extractAmount(message),
    reference: extractReference(message),
    customerPhone: extractPhone(message),
    warnings: ["Parsed with fallback SMS parser"],
    minimumConfidence: 0.6,
  });
}

export function parseInboundSmsMessage(
  message: string,
  providerHint?: SmsProvider,
  sender?: string
): ParsedSmsResult {
  const detectedProvider = detectProvider(message, sender, providerHint);
  const parser = parserModules.find((candidate) => candidate.provider === detectedProvider);

  if (!parser) {
    return fallbackParse(message, providerHint);
  }

  const parsed = parser.parse(message, sender);

  if (providerHint && providerHint !== "UNKNOWN" && parsed.provider !== providerHint) {
    return {
      ...parsed,
      warnings: [...parsed.warnings, `Provider hint ${providerHint} differed from detected ${parsed.provider}`],
    };
  }

  return parsed;
}

export const smsParserFixtures: SmsParserFixture[] = [
  {
    scenario: "deposit",
    provider: "MPESA",
    sender: "M-Pesa",
    message: "QJH7K2LMN8 Confirmed. Umepokea TZS 45,000 kutoka 0712345678. Salio lako ni TZS 120,000. M-Pesa Wakala.",
    expected: {
      provider: "MPESA",
      type: "DEPOSIT",
      amount: 45000,
      reference: "QJH7K2LMN8",
      customerPhone: "0712345678",
      minimumConfidence: 0.75,
      parseError: null,
    },
  },
  {
    scenario: "deposit",
    provider: "AIRTEL_MONEY",
    sender: "Airtel Money",
    message: "TXN ID AX91PLK33. Airtel Money cash in received. Amount: TZS 120,000 from 0755123456. New balance TZS 1,400,000.",
    expected: {
      provider: "AIRTEL_MONEY",
      type: "DEPOSIT",
      amount: 120000,
      reference: "AX91PLK33",
      customerPhone: "0755123456",
      minimumConfidence: 0.75,
      parseError: null,
    },
  },
  {
    scenario: "transfer",
    provider: "MIXX_BY_YAS",
    sender: "Mixx by Yas",
    message: "Receipt MX44PQL991. Mixx by Yas transfer confirmed. Amount TZS 30,000 sent to 0655123456. Fee TZS 500.",
    expected: {
      provider: "MIXX_BY_YAS",
      type: "TRANSFER",
      amount: 30000,
      reference: "MX44PQL991",
      customerPhone: "0655123456",
      minimumConfidence: 0.75,
      parseError: null,
    },
  },
  {
    scenario: "deposit",
    provider: "HALOPESA",
    sender: "Halopesa",
    message: "HP88ZXQ112 Confirmed. Umepokea TZS 65,000 kutoka 0623456789. Salio jipya ni TZS 300,000.",
    expected: {
      provider: "HALOPESA",
      type: "DEPOSIT",
      amount: 65000,
      reference: "HP88ZXQ112",
      customerPhone: "0623456789",
      minimumConfidence: 0.75,
      parseError: null,
    },
  },
  {
    scenario: "deposit",
    provider: "CRDB_BANK",
    sender: "CRDB",
    message: "Reference CRD912AB33. Cash deposit confirmed. Amount: TZS 150,000 from 0711122233. CRDB Biashara Alerts.",
    expected: {
      provider: "CRDB_BANK",
      type: "BANK_DEPOSIT",
      amount: 150000,
      reference: "CRD912AB33",
      customerPhone: "0711122233",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "withdrawal",
    provider: "NMB_BANK",
    sender: "NMB Alerts",
    message: "Receipt NMB44PPQ77. Cash withdrawal confirmed. Amount TZS 80,000 to 0788123456. NMB Bank.",
    expected: {
      provider: "NMB_BANK",
      type: "BANK_WITHDRAWAL",
      amount: 80000,
      reference: "NMB44PPQ77",
      customerPhone: "0788123456",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "bill_payment",
    provider: "SELCOM_PESA",
    sender: "Selcom Pesa",
    message: "SP22LLM882 Receipt. Bill payment confirmed. Amount: TZS 25,000 from 0766123456. Control number accepted.",
    expected: {
      provider: "SELCOM_PESA",
      type: "BILL_PAYMENT",
      amount: 25000,
      reference: "SP22LLM882",
      customerPhone: "0766123456",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "withdrawal",
    provider: "MPESA",
    sender: "M-Pesa",
    message: "QP11ABC992 Confirmed. Cash out TZS 20,000 to 0711111111 completed. M-Pesa Wakala.",
    expected: {
      provider: "MPESA",
      type: "WITHDRAWAL",
      amount: 20000,
      reference: "QP11ABC992",
      customerPhone: "0711111111",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "float_purchase",
    provider: "MPESA",
    sender: "M-Pesa",
    message: "Float top up confirmed. Receipt MPFLOT7788. Amount TZS 100,000. M-Pesa business line updated.",
    expected: {
      provider: "MPESA",
      type: "FLOAT_PURCHASE",
      amount: 100000,
      reference: "MPFLOT7788",
      customerPhone: undefined,
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "bill_payment",
    provider: "MPESA",
    sender: "M-Pesa",
    message: "Receipt MPBILL5522. Bill payment confirmed. Amount TZS 18,000 from 0712233445. Control number accepted.",
    expected: {
      provider: "MPESA",
      type: "BILL_PAYMENT",
      amount: 18000,
      reference: "MPBILL5522",
      customerPhone: "0712233445",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "noisy",
    provider: "MPESA",
    sender: "M-Pesa",
    message: "M-Pesa service notice: system maintenance tonight from 1AM to 3AM.",
    expected: {
      provider: "MPESA",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "withdrawal",
    provider: "AIRTEL_MONEY",
    sender: "Airtel Money",
    message: "Receipt AMW998821. Airtel Money withdrawal confirmed. Amount: TZS 55,000 to 0755001122.",
    expected: {
      provider: "AIRTEL_MONEY",
      type: "WITHDRAWAL",
      amount: 55000,
      reference: "AMW998821",
      customerPhone: "0755001122",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "transfer",
    provider: "AIRTEL_MONEY",
    sender: "Airtel Money",
    message: "TXN ID ATR223PL9. Airtel Money transfer successful. Amount: TZS 40,000 sent to 0755223344.",
    expected: {
      provider: "AIRTEL_MONEY",
      type: "TRANSFER",
      amount: 40000,
      reference: "ATR223PL9",
      customerPhone: "0755223344",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "float_purchase",
    provider: "AIRTEL_MONEY",
    sender: "Airtel Money",
    message: "Receipt AFL442991. Float top up confirmed. Amount: TZS 250,000. Airtel Money line updated.",
    expected: {
      provider: "AIRTEL_MONEY",
      type: "FLOAT_PURCHASE",
      amount: 250000,
      reference: "AFL442991",
      customerPhone: undefined,
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "bill_payment",
    provider: "AIRTEL_MONEY",
    sender: "Airtel Money",
    message: "Receipt ABP110022. Bill payment successful. Amount: TZS 12,000 from 0755334455. Control number cleared.",
    expected: {
      provider: "AIRTEL_MONEY",
      type: "BILL_PAYMENT",
      amount: 12000,
      reference: "ABP110022",
      customerPhone: "0755334455",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "noisy",
    provider: "AIRTEL_MONEY",
    sender: "Airtel Money",
    message: "Airtel Money reminder: keep your PIN secret and never share it with anyone.",
    expected: {
      provider: "AIRTEL_MONEY",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "deposit",
    provider: "MIXX_BY_YAS",
    sender: "Mixx by Yas",
    message: "Receipt MYD119900. Mixx by Yas deposit confirmed. Amount TZS 90,000 received from 0655998877.",
    expected: {
      provider: "MIXX_BY_YAS",
      type: "DEPOSIT",
      amount: 90000,
      reference: "MYD119900",
      customerPhone: "0655998877",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "withdrawal",
    provider: "MIXX_BY_YAS",
    sender: "Mixx by Yas",
    message: "Receipt MYW778822. Mixx by Yas withdrawal confirmed. Amount TZS 35,000 to 0655443322.",
    expected: {
      provider: "MIXX_BY_YAS",
      type: "WITHDRAWAL",
      amount: 35000,
      reference: "MYW778822",
      customerPhone: "0655443322",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "float_purchase",
    provider: "MIXX_BY_YAS",
    sender: "Mixx by Yas",
    message: "Receipt MYF220011. Mixx by Yas float top up confirmed. Amount TZS 180,000.",
    expected: {
      provider: "MIXX_BY_YAS",
      type: "FLOAT_PURCHASE",
      amount: 180000,
      reference: "MYF220011",
      customerPhone: undefined,
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "bill_payment",
    provider: "MIXX_BY_YAS",
    sender: "Mixx by Yas",
    message: "Receipt MYB553311. Bill payment confirmed. Amount TZS 22,000 from 0655778899. Control number updated.",
    expected: {
      provider: "MIXX_BY_YAS",
      type: "BILL_PAYMENT",
      amount: 22000,
      reference: "MYB553311",
      customerPhone: "0655778899",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "noisy",
    provider: "MIXX_BY_YAS",
    sender: "Mixx by Yas",
    message: "Mixx by Yas campaign update: enjoy zero charges this weekend.",
    expected: {
      provider: "MIXX_BY_YAS",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "withdrawal",
    provider: "HALOPESA",
    sender: "Halopesa",
    message: "HLW662211 Confirmed. Cash out TZS 44,000 to 0623002211 completed.",
    expected: {
      provider: "HALOPESA",
      type: "WITHDRAWAL",
      amount: 44000,
      reference: "HLW662211",
      customerPhone: "0623002211",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "transfer",
    provider: "HALOPESA",
    sender: "Halopesa",
    message: "HLT882244 Transfer confirmed. Amount TZS 30,000 sent to 0623445566.",
    expected: {
      provider: "HALOPESA",
      type: "TRANSFER",
      amount: 30000,
      reference: "HLT882244",
      customerPhone: "0623445566",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "float_purchase",
    provider: "HALOPESA",
    sender: "Halopesa",
    message: "HLF991122 Float top up confirmed. Amount TZS 210,000.",
    expected: {
      provider: "HALOPESA",
      type: "FLOAT_PURCHASE",
      amount: 210000,
      reference: "HLF991122",
      customerPhone: undefined,
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "bill_payment",
    provider: "HALOPESA",
    sender: "Halopesa",
    message: "HLB330011 Bill payment confirmed. Amount TZS 19,000 from 0623889900. Control number accepted.",
    expected: {
      provider: "HALOPESA",
      type: "BILL_PAYMENT",
      amount: 19000,
      reference: "HLB330011",
      customerPhone: "0623889900",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "noisy",
    provider: "HALOPESA",
    sender: "Halopesa",
    message: "Halopesa reminder: update your app to the latest version today.",
    expected: {
      provider: "HALOPESA",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "withdrawal",
    provider: "CRDB_BANK",
    sender: "CRDB",
    message: "Reference CRW440099. Cash withdrawal confirmed. Amount: TZS 60,000 to 0711556677. CRDB Bank.",
    expected: {
      provider: "CRDB_BANK",
      type: "BANK_WITHDRAWAL",
      amount: 60000,
      reference: "CRW440099",
      customerPhone: "0711556677",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "transfer",
    provider: "CRDB_BANK",
    sender: "CRDB Biashara",
    message: "Transaction ID CRT554211. Funds transfer successful. Amount: TZS 140,000 to 0711667788.",
    expected: {
      provider: "CRDB_BANK",
      type: "TRANSFER",
      amount: 140000,
      reference: "CRT554211",
      customerPhone: "0711667788",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "float_purchase",
    provider: "CRDB_BANK",
    sender: "CRDB",
    message: "Reference CRF001188. Float purchase confirmed. Amount: TZS 300,000 from 0711223344.",
    expected: {
      provider: "CRDB_BANK",
      type: undefined,
      amount: 300000,
      reference: "CRF001188",
      customerPhone: "0711223344",
      minimumConfidence: 0.3,
      maximumConfidence: 0.55,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "bill_payment",
    provider: "CRDB_BANK",
    sender: "CRDB",
    message: "Reference CRB770011. Bill payment processed. Amount: TZS 17,000 from 0711778899.",
    expected: {
      provider: "CRDB_BANK",
      type: undefined,
      amount: 17000,
      reference: "CRB770011",
      customerPhone: "0711778899",
      minimumConfidence: 0.3,
      maximumConfidence: 0.55,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "noisy",
    provider: "CRDB_BANK",
    sender: "CRDB",
    message: "CRDB reminder: your monthly statement is ready for download.",
    expected: {
      provider: "CRDB_BANK",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "deposit",
    provider: "NMB_BANK",
    sender: "NMB Alerts",
    message: "Receipt NMD110022. Cash deposit confirmed. Amount TZS 200,000 from 0788001122. NMB Bank.",
    expected: {
      provider: "NMB_BANK",
      type: "BANK_DEPOSIT",
      amount: 200000,
      reference: "NMD110022",
      customerPhone: "0788001122",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "transfer",
    provider: "NMB_BANK",
    sender: "NMB Alerts",
    message: "Transaction ID NMT771100. Fund transfer successful. Amount TZS 95,000 to 0788112233.",
    expected: {
      provider: "NMB_BANK",
      type: "TRANSFER",
      amount: 95000,
      reference: "NMT771100",
      customerPhone: "0788112233",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "float_purchase",
    provider: "NMB_BANK",
    sender: "NMB Alerts",
    message: "Receipt NMF881199. Float purchase confirmed. Amount TZS 260,000 from 0788223344.",
    expected: {
      provider: "NMB_BANK",
      type: undefined,
      amount: 260000,
      reference: "NMF881199",
      customerPhone: "0788223344",
      minimumConfidence: 0.3,
      maximumConfidence: 0.55,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "bill_payment",
    provider: "NMB_BANK",
    sender: "NMB Alerts",
    message: "Receipt NMB110044. Bill payment processed. Amount TZS 16,000 from 0788334455.",
    expected: {
      provider: "NMB_BANK",
      type: undefined,
      amount: 16000,
      reference: "NMB110044",
      customerPhone: "0788334455",
      minimumConfidence: 0.3,
      maximumConfidence: 0.55,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "noisy",
    provider: "NMB_BANK",
    sender: "NMB Alerts",
    message: "NMB alert: update your account details at your nearest branch.",
    expected: {
      provider: "NMB_BANK",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "deposit",
    provider: "SELCOM_PESA",
    sender: "Selcom Pesa",
    message: "SPD778811 Receipt. Umepokea TZS 47,000 kutoka 0766001122. Selcom Pesa.",
    expected: {
      provider: "SELCOM_PESA",
      type: "DEPOSIT",
      amount: 47000,
      reference: "SPD778811",
      customerPhone: "0766001122",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "withdrawal",
    provider: "SELCOM_PESA",
    sender: "Selcom Pesa",
    message: "SPW229911 Receipt. Withdrawal confirmed. Amount TZS 27,000 to 0766112233.",
    expected: {
      provider: "SELCOM_PESA",
      type: "WITHDRAWAL",
      amount: 27000,
      reference: "SPW229911",
      customerPhone: "0766112233",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "transfer",
    provider: "SELCOM_PESA",
    sender: "Selcom Pesa",
    message: "SPT001177 Receipt. Transfer successful. Amount TZS 38,000 sent to 0766223344.",
    expected: {
      provider: "SELCOM_PESA",
      type: "TRANSFER",
      amount: 38000,
      reference: "SPT001177",
      customerPhone: "0766223344",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "float_purchase",
    provider: "SELCOM_PESA",
    sender: "Selcom Pesa",
    message: "SPF771144 Receipt. Float top up confirmed. Amount TZS 190,000.",
    expected: {
      provider: "SELCOM_PESA",
      type: undefined,
      amount: 190000,
      reference: "SPF771144",
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.55,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "noisy",
    provider: "SELCOM_PESA",
    sender: "Selcom Pesa",
    message: "Selcom Pesa promo: enjoy discounted transfers this Friday only.",
    expected: {
      provider: "SELCOM_PESA",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
    },
  },
  {
    scenario: "sender_alias",
    provider: "MPESA",
    sender: "Vodacom M-Pesa",
    message: "QXZ778PL11 Confirmed. Umepokea TZS 54,000 kutoka 0712003344. Salio lako ni TZS 200,000.",
    expected: {
      provider: "MPESA",
      type: "DEPOSIT",
      amount: 54000,
      reference: "QXZ778PL11",
      customerPhone: "0712003344",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "mixed_language",
    provider: "AIRTEL_MONEY",
    sender: "Airtel TZ",
    message: "Txn ID ALT220011 confirmed. Umepokea TZS 33,000 from 0755442211. New balance ni TZS 120,000.",
    expected: {
      provider: "AIRTEL_MONEY",
      type: "DEPOSIT",
      amount: 33000,
      reference: "ALT220011",
      customerPhone: "0755442211",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "failed",
    provider: "MIXX_BY_YAS",
    sender: "YAS Money",
    message: "Receipt MYF882211. Mixx by Yas transfer failed. Amount TZS 41,000 to 0655007788 was unsuccessful.",
    expected: {
      provider: "MIXX_BY_YAS",
      type: "TRANSFER",
      amount: 41000,
      reference: "MYF882211",
      customerPhone: "0655007788",
      minimumConfidence: 0.72,
      parseError: null,
      warningIncludes: ["failed transaction"],
    },
  },
  {
    scenario: "reversal",
    provider: "HALOPESA",
    sender: "Halo-Pesa",
    message: "HLR990011 Reversal notice. Cash out ya TZS 28,000 kwa 0623008899 imerejeshwa. Ref HLR990011.",
    expected: {
      provider: "HALOPESA",
      type: undefined,
      amount: 28000,
      reference: "HLR990011",
      customerPhone: "0623008899",
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
      warningIncludes: ["reversal or reversal notice"],
    },
  },
  {
    scenario: "provider_warning",
    provider: "CRDB_BANK",
    sender: "CRDB Alerts",
    message: "CRDB warning: never share your PIN or OTP with anyone. Fraud alert for all agents.",
    expected: {
      provider: "CRDB_BANK",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
      warningIncludes: ["provider warning or informational notice"],
    },
  },
  {
    scenario: "sender_alias",
    provider: "NMB_BANK",
    sender: "NMB Huduma",
    message: "Receipt NMA778844. Cash deposit confirmed. Amount TZS 88,000 from 0788007766.",
    expected: {
      provider: "NMB_BANK",
      type: "BANK_DEPOSIT",
      amount: 88000,
      reference: "NMA778844",
      customerPhone: "0788007766",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "mixed_language",
    provider: "SELCOM_PESA",
    sender: "Selcom SMS",
    message: "SPM221144 Receipt. Umepokea TZS 29,000 from 0766332211. Salio new ni TZS 77,000.",
    expected: {
      provider: "SELCOM_PESA",
      type: "DEPOSIT",
      amount: 29000,
      reference: "SPM221144",
      customerPhone: "0766332211",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "failed",
    provider: "MPESA",
    sender: "M-Pesa TZ",
    message: "QFL221188 Transaction failed. Kutuma TZS 15,000 kwenda 0712556677 haikufanikiwa.",
    expected: {
      provider: "MPESA",
      type: "TRANSFER",
      amount: 15000,
      reference: "QFL221188",
      customerPhone: "0712556677",
      minimumConfidence: 0.72,
      parseError: null,
      warningIncludes: ["failed transaction"],
    },
  },
  {
    scenario: "reversal",
    provider: "AIRTEL_MONEY",
    sender: "AirtelMoney",
    message: "Txn ID ARV110099. Reversed transaction. TZS 22,000 to 0755112233 imerejeshwa kwa akaunti yako.",
    expected: {
      provider: "AIRTEL_MONEY",
      type: undefined,
      amount: 22000,
      reference: "ARV110099",
      customerPhone: "0755112233",
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
      warningIncludes: ["reversal or reversal notice"],
    },
  },
  {
    scenario: "provider_warning",
    provider: "MIXX_BY_YAS",
    sender: "Mixx by Yas",
    message: "Mixx by Yas alert: keep your PIN secret. Usishiriki namba yako ya siri na mtu yeyote.",
    expected: {
      provider: "MIXX_BY_YAS",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
      warningIncludes: ["provider warning or informational notice"],
    },
  },
  {
    scenario: "sender_alias",
    provider: "CRDB_BANK",
    sender: "CRDBBank",
    message: "Receipt CRA554422. Cash withdrawal confirmed. Amount: TZS 73,000 to 0711445566.",
    expected: {
      provider: "CRDB_BANK",
      type: "BANK_WITHDRAWAL",
      amount: 73000,
      reference: "CRA554422",
      customerPhone: "0711445566",
      minimumConfidence: 0.72,
      parseError: null,
    },
  },
  {
    scenario: "provider_warning",
    provider: "NMB_BANK",
    sender: "NMB Alerts",
    message: "NMB alert: fraud notice. Never share your PIN or one-time password with anyone.",
    expected: {
      provider: "NMB_BANK",
      type: undefined,
      amount: undefined,
      reference: undefined,
      customerPhone: undefined,
      minimumConfidence: 0.3,
      maximumConfidence: 0.5,
      parseError: "Could not confidently determine provider, type, and amount from the SMS",
      warningIncludes: ["provider warning or informational notice"],
    },
  },
  {
    scenario: "failed",
    provider: "SELCOM_PESA",
    sender: "SelcomPesa",
    message: "Receipt SPF009922. Transfer to 0766002211 failed. Amount TZS 31,000 haikufanikiwa.",
    expected: {
      provider: "SELCOM_PESA",
      type: "TRANSFER",
      amount: 31000,
      reference: "SPF009922",
      customerPhone: "0766002211",
      minimumConfidence: 0.72,
      parseError: null,
      warningIncludes: ["failed transaction"],
    },
  },
];
